version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    container_name: pong_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pong_user
      - POSTGRES_DB=pong
      - POSTGRES_PASSWORD=
  redis:
    image: redis:5.0.5-alpine
    container_name: pong_redis
    ports:
      - 9001:6379

